// Data.js
export const products = [
  {
    id: 1,
    image: "/pic1.jpeg",
    title: "Product 1",
    price: "$20",
    images: ["/pic1.jpeg", "/pic1p2.jpeg"],
    description: [
      "Beige Collar Polo Shirt",
      "Fit type: Regular fit",
      "Design details: Johnny collar polo made of neoprene fabric with short sleeves featuring side slits",
      "Stretch: High",
      "Transparency: None",
      "Hand feel: Soft",
      "Lining: None",
      "Material: 50% Rayon 45% Polyester 5% Spandex",
    ],
    category: "men",
  },
  {
    id: 2,
    image: "/pic2.jpeg",
    title: "Product 2",
    price: "$25",
    images: ["/pic2.jpeg", "/pic2p1.jpeg"],
    description: [
      "      Straight Leg Pants",
      "Fit type: Relaxed fit",
      "Design details: :Neoprene pants designed with side-seam pockets and a belted waistband for a sleek, functional silhouette.",
      "Stretch: High",
      "Transparency: Not transparent",
      "Hand feel: Soft",
      "Lining: None",
      "Material: 50％ Rayon 45％ Polyester 5％ Spandex",
    ],
    category: "women", // Example category
  },
  {
    id: 3,
    image: "/pic3.jpeg",
    title: "Product 3",
    price: "$30",
    images: ["/pic3.jpeg"],
    description: [
      "Hooded Puffer Jacket",
      "   Fit type: Regular fit",
      "Design details: Hooded jacket with a fur lining, adjustable drawstring at the waist, and a detachable fur patch for the hood. It includes cross pockets adorned with buckle and button details on the pocket welt, along with a front zip closure.",
      "Stretch: None",
      "Transparency: Not transparent ",
      "Hand feel: Soft ",
      "Lining: Fur Lining",
      "  Material: 100% Polyester",
    ],
    category: "men", // Example category
  },
  {
    id: 4,
    image: "/pic4.jpeg",
    title: "Product 4",
    price: "$30",
    images: ["/pic4.jpeg"],
    description: [
      "Neck Fleece Sweatshirt",
      "PKR 3990",
      "Fit type: Regular fit",
      "Design details: Made with cozy fleece material, this shirt offers ultimate comfort and a trendy mock neck design.",
      "Transparency: Not transparent ",
      "Hand feel: Soft",
      "Material: 60% Cotton, 40% Polyester",
    ],
    category: "women", // Example category
  },
  {
    id: 5,
    image: "/pic5.jpeg",
    title: "Product 5",
    price: "$30",
    images: ["/pic5.jpeg"],
    description: [
      "Oversized Tee",
      "Rs. 2,750",
      "Fit type: Relaxed fit",
      "Design details: Printed crew neck, drop shoulder, short sleeves.",
      "Stretch: High",
      "Transparency: Not transparent",
      "Hand feel: Soft",
      "Lining: None",
      "Material: 95% Cotton, 5% Lycra",
    ],
    category: "men", // Example category
  },
  {
    id: 6,
    image: "/pic6.jpeg",
    title: "Product 6",
    price: "$30",
    images: ["/pic6.jpeg", "/pic6p2.jpeg"],
    description: [
      "White Adjustable Pants",
      "Rs. 7,950",
      "Fit type: Tailored",
      "Design detail: Adjustable pants with elasticated waistband and front pleat",
      "Stretch: Medium",
      "Lining: None",
      "Transparency: Not Transparent",
      "Hand feel: Soft",
      "Material: Terry",
    ],
    category: "women", // Example category
  },
  {
    id: 7,
    image: "/pic7.jpeg",
    title: "Product 7",
    price: "$30",
    images: ["/pic7.jpeg"],
    description: [
      "Jacquard Trouser",
      "Rs. 6,950",
      "Fit type: Tapered Fit",
      "Design details: Tapered fit bottoms with drawstring featuring side pockets",
      "Stretch: Low",
      "Transparency: None",
      "Hand feel: soft",
      "Lining: None",
      "Material: 65% Cotton, 30% Polyester, 5% Spandex",
    ],
    category: "men", // Example category
  },
  {
    id: 8,
    image: "/pic8.jpeg",
    title: "Product 8",
    price: "$30",
    images: ["/pic8.jpeg"],
    description: [
      "High Crew Jumper",
      "Rs 6950",
      "Fit type: Relaxed",
      "Design details: Mock neck sweater, Dropped shoulder with ribbed trim details",
      "Stretch: High",
      "Transparency: None",
      "Hand feel: Soft",
      "Lining: None",
      "Material: 50%Adhesive,30% Nylon,20% Polyester",
    ],
    category: "women", // Example category
  },
  {
    id: 9,
    image: "/pic9.jpeg",
    title: "Product 9",
    price: "$30",
    images: ["/pic9.jpeg"],
    description: [
      "Contrast Gilet",
      "Rs. 8,450",
      "Fit type: Regular",
      "Design detail: Sleeveless puffer jacket with detachable Hood. Side zip pockets, front zipper with interior pocket. Contrast Panels.",
      "Stretch: None",
      "Transparency: None",
      "Hand feel: Soft",
      "Lining: Yes, 100% Polyester",
      "Material: 100 % Polyester",
    ],
    category: "men", // Example category
  },
  {
    id: 10,
    image: "/pic10.jpeg",
    title: "Product 10",
    price: "$30",
    images: ["/pic10.jpeg", "/pic10p2.jpeg"],
    description: [
      "Embroidered SweatShirt",
      "Rs. 4,950",
      "Fit type: Regular fit",
      "Design details: Sweatshirt made of cotton mix yarn. Round neck and long sleeves. Featuring a pear embroidery detail on the front.",
      "Stretch: High",
      "Transparency: None",
      "Hand feel: Regular",
      "Lining: None",
      "Material: 95% Cotton,5% Spandex",
    ],
    category: "women",
  },
];

export const navdData = [
  { name: "Home", href: "/" },
  { name: "About", href: "/About" },
  { name: "Contact", href: "/Contact" },
];
